<script setup lang="ts">
import { Download, ImagePlus, RotateCcw, X } from "lucide-vue-next";
import { thumbnailTemplates, type ThumbnailState } from "./types";
defineProps<{ state: ThumbnailState; exporting: boolean }>();
const emit = defineEmits<{ (event: "update:title", value: string): void; (event: "update:template", value: ThumbnailState["template"]): void; (event: "update:image", file: File | null): void; (event: "update:before-image", file: File | null): void; (event: "update:after-image", file: File | null): void; (event: "update:scale", value: number): void; (event: "update:x", value: number): void; (event: "update:y", value: number): void; (event: "reset"): void; (event: "export"): void; }>();
const readFile = (event: Event, target: "image" | "before-image" | "after-image") => { const input = event.target as HTMLInputElement; const file = input.files?.[0] ?? null; if (target === "image") emit("update:image", file); if (target === "before-image") emit("update:before-image", file); if (target === "after-image") emit("update:after-image", file); input.value = ""; };
</script>
<template>
  <section class="border-2 border-[var(--ui-border)] border-r-[var(--ui-border-dark)] border-b-[var(--ui-border-dark)] bg-[var(--ui-bg)] text-[var(--ui-text)] shadow-[5px_5px_0_rgb(0_0_0_/_0.55)]" aria-label="Controles da thumbnail">
    <div class="flex items-center justify-between bg-gradient-to-r from-[var(--ts-primary-pink)] to-[var(--ts-secondary-black)] px-2.5 py-2 text-[.7rem] font-extrabold tracking-[.08em] text-white"><p class="m-0">Thumbnail_Control_Panel.exe</p><X class="box-content h-5 w-5 border border-white p-0" :size="14" /></div>
    <div class="grid gap-4 p-4">
      <label class="grid gap-1.5 text-[.68rem] font-extrabold tracking-[.06em]"><p class="m-0">TEMPLATE</p><select class="min-h-10 border-2 border-[var(--ui-border-dark)] bg-white px-2 py-1.5 text-[#26051b]" :value="state.template" @change="emit('update:template', ($event.target as HTMLSelectElement).value as ThumbnailState['template'])"><option v-for="template in thumbnailTemplates" :key="template.id" :value="template.id">{{ template.label }}</option></select></label>
      <label class="grid gap-1.5 text-[.68rem] font-extrabold tracking-[.06em]"><p class="m-0">HEADLINE</p><input class="min-h-10 border-2 border-[var(--ui-border-dark)] bg-white px-2 py-1.5 text-[#26051b]" :value="state.title" type="text" maxlength="72" placeholder="LEARNING HOW TO DRAW..." @input="emit('update:title', ($event.target as HTMLInputElement).value)"></label>
      <div v-if="state.template === 'before-after'" class="grid grid-cols-2 gap-2.5 max-[380px]:grid-cols-1"><label v-for="target in ['before-image', 'after-image'] as const" :key="target" class="flex min-h-16 cursor-pointer items-center justify-center gap-2 border-2 border-dashed border-[var(--ui-border-dark)] bg-[color:color-mix(in_srgb,var(--ui-bg-secondary)_68%,white)] p-3 text-center text-[.63rem] font-extrabold tracking-[.05em] hover:bg-[var(--ui-bg-tertiary)]"><ImagePlus :size="18" /><p class="m-0">UPLOAD {{ target === 'before-image' ? 'BEFORE' : 'AFTER' }}</p><input class="sr-only" type="file" accept="image/png,image/jpeg,image/webp" @change="readFile($event, target)"></label></div>
      <label v-else class="flex min-h-16 cursor-pointer items-center justify-center gap-2 border-2 border-dashed border-[var(--ui-border-dark)] bg-[color:color-mix(in_srgb,var(--ui-bg-secondary)_68%,white)] p-3 text-center text-[.63rem] font-extrabold tracking-[.05em] hover:bg-[var(--ui-bg-tertiary)]"><ImagePlus :size="18" /><p class="m-0">UPLOAD ARTWORK</p><input class="sr-only" type="file" accept="image/png,image/jpeg,image/webp" @change="readFile($event, 'image')"></label>
      <fieldset v-if="state.template !== 'before-after'" class="grid gap-3 border-2 border-[var(--ui-border)] p-3"><legend class="px-1 text-[.63rem] font-extrabold tracking-[.06em]">ARTWORK POSITION</legend><label v-for="control in [{key:'scale',label:'ZOOM',value:state.imageScale,min:.6,max:2.4,step:.01},{key:'x',label:'HORIZONTAL',value:state.imageX,min:-50,max:50,step:1},{key:'y',label:'VERTICAL',value:state.imageY,min:-50,max:50,step:1}]" :key="control.key" class="grid gap-1.5 text-[.68rem] font-extrabold tracking-[.06em]"><p class="m-0">{{ control.label }} {{ control.key === 'scale' ? `${control.value.toFixed(2)}×` : `${control.value}%` }}</p><input class="w-full accent-[var(--ts-primary-pink)]" :value="control.value" type="range" :min="control.min" :max="control.max" :step="control.step" @input="emit(`update:${control.key}` as 'update:scale', Number(($event.target as HTMLInputElement).value))"></label></fieldset>
      <div class="grid grid-cols-[.85fr_1.15fr] gap-2.5 max-[380px]:grid-cols-1"><button type="button" class="inline-flex min-h-11 items-center justify-center gap-1.5 border-2 border-[#250018] bg-white p-2 text-[.68rem] font-black tracking-[.06em] text-[#250018] shadow-[2px_2px_0_#250018] active:translate-x-0.5 active:translate-y-0.5 active:shadow-none" @click="emit('reset')"><RotateCcw :size="15" /> RESET</button><button type="button" class="inline-flex min-h-11 items-center justify-center gap-1.5 border-2 border-[#250018] bg-[var(--ts-primary-pink)] p-2 text-[.68rem] font-black tracking-[.06em] text-white shadow-[2px_2px_0_#250018] active:translate-x-0.5 active:translate-y-0.5 active:shadow-none disabled:cursor-wait disabled:opacity-65" :disabled="exporting" @click="emit('export')"><Download :size="16" /> {{ exporting ? 'EXPORTING...' : 'EXPORT PNG' }}</button></div>
      <p class="m-0 border-t border-dashed border-[var(--ui-border-dark)] pt-3 text-[.58rem] font-extrabold tracking-[.05em] text-[var(--ui-text-soft)]">LOCAL MODE: images stay in your browser.</p>
    </div>
  </section>
</template>
